### ISSUE TITLE
I just configure as you mentioned but I can't get the ''meta'' in the response

### ISSUE THREAD

**Issue by bete-hub** [prototype-berlin/loopback-paginator#8]
Model Config
"mixins": {
    "Paginator": true
  }

model-config.json
"_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../node_modules/loopback-paginator",
      "../common/mixins",
      "./mixins"
    ]
  }

package.json

"dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^3.10.0",
    "loopback": "^3.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^6.2.0",
    "loopback-component-storage": "^3.6.3",
    "loopback-connector-mongodb": "^4.2.0",
    "loopback-paginator": "^3.0.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^3.0.0"
  }

**Comment by mahnuh** [comment]
Did you add `?page=1` to the requested URL?

**Comment by bete-hub** [comment]
Thanks a lot, it works.
