### ISSUE TITLE
Pagination is not working for Users model

### ISSUE THREAD

**Issue by kritsanaCh57** [prototype-berlin/loopback-paginator#9]
Hi, I setup pagination for User model but i tried to fetch `/Users?page=1` and it didn't work.

**Infomation**:
- `"loopback": "^3.22.0"`
- `"loopback-paginator": "^3.0.0"`
- `"loopback-connector-mongodb": "^5.2.2"`

**Example Code:**
```
 # model-config.json
  ...
  "User": {
    ....
    "mixins": {
      "Paginator": {
        "limit": 5,
        "maxLimit": 20
      }
    },
 }
 ...
```

**Response actually:**
```
[{...user...}]
```

 **Response expected:**
```
data: [{...user...}],
meta: {
  currentPage: xxx
  itemsPerPage: xxx
  totalItemCount: xxx
  totalPageCount: xxx
}
```

**Comment by mahnuh** [comment]
Hi @kritsanaCh57,

does it work with your custom models?

**Comment by kritsanaCh57** [comment]
@mahnuh 
yes, custom model is working

**Comment by mahnuh** [comment]
@kritsanaCh57 I see. I think you are not able to configure mixins in model-config.json acccording to the [docs](https://loopback.io/doc/en/lb3/model-config.json.html).
You could create a custom user model with User as base model and then add the paginator mixin.

**Comment by kritsanaCh57** [comment]
@mahnuh OK, Thank you  :)
